Repository nimblehq/ic-rails-huey-toby, pull requests merged in 2023-07, with the labels that each got.

#43 [#9] [Backend] As a user, I can sign-up with Google
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/users/omniauth_callbacks_controller.rb
  app/models/user.rb
  config/application.yml
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20230626042619_devise_create_users.rb
  db/schema.rb
  spec/fabricators/user_fabricator.rb
  spec/models/user_spec.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
  spec/support/omniauth_helpers.rb
Labels: type : feature

#45 [#11][#22] [Backend] As a user, I must be authorized to upload keywords
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/search_results_controller.rb
  app/controllers/api/v1/users/omniauth_callbacks_controller.rb
  app/models/oauth_token.rb
  app/models/user.rb
  app/serializers/oauth_token_serializer.rb
  config/initializers/devise.rb
  config/initializers/doorkeeper.rb
  config/locales/activemodel.en.yml
  config/locales/doorkeeper.en.yml
  config/routes.rb
  db/migrate/20230703043059_enable_pgcrypto_extension.rb
  db/migrate/20230704091131_update_id_column_of_users.rb
  db/migrate/20230704102430_create_doorkeeper_tables.rb
  db/migrate/20230707024057_create_default_oauth_application.rb
  db/schema.rb
  db/seeds.rb
  spec/fabricators/access_token_fabricator.rb
  spec/fabricators/application_fabricator.rb
  spec/models/oauth_token_spec.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
  spec/requests/search_results_controller_spec.rb
  spec/support/authentication_helpers.rb
Labels: type : feature

#47 Release - 0.5.0
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/search_results_controller.rb
  app/controllers/api/v1/users/omniauth_callbacks_controller.rb
  app/models/oauth_token.rb
  app/models/user.rb
  app/serializers/oauth_token_serializer.rb
  config/application.yml
  config/initializers/devise.rb
  config/initializers/doorkeeper.rb
  config/locales/activemodel.en.yml
  config/locales/doorkeeper.en.yml
  config/routes.rb
  db/migrate/20230626042619_devise_create_users.rb
  db/migrate/20230703043059_enable_pgcrypto_extension.rb
  db/migrate/20230704091131_update_id_column_of_users.rb
  db/migrate/20230704102430_create_doorkeeper_tables.rb
  db/migrate/20230707024057_create_default_oauth_application.rb
  db/schema.rb
  db/seeds.rb
  spec/fabricators/access_token_fabricator.rb
  spec/fabricators/application_fabricator.rb
  spec/fabricators/user_fabricator.rb
  spec/models/oauth_token_spec.rb
  spec/models/user_spec.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
  spec/requests/search_results_controller_spec.rb
  spec/support/authentication_helpers.rb
  spec/support/omniauth_helpers.rb
Labels: type : release

#46 [#13][Backend] As a user, I can see the list of search results
  app/controllers/api/v1/search_results_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/error_handleable.rb
  app/controllers/concerns/has_doorkeeper_authentication.rb
  app/controllers/concerns/has_pagination.rb
  app/forms/upload_form.rb
  app/models/search_result.rb
  app/models/user.rb
  config/initializers/pagy.rb
  config/routes.rb
  db/migrate/20230706033605_add_user_id_to_search_results.rb
  db/schema.rb
  spec/fabricators/search_result_fabricator.rb
  spec/forms/upload_form_spec.rb
  spec/jobs/search_keyword_job_spec.rb
  spec/requests/search_results_controller_spec.rb
  spec/support/authentication_helpers.rb
Labels: type : feature

#48 [#10] [Backend] As a user, I can sign-in with e-mail and password
  app/controllers/api/v1/search_results_controller.rb
  app/controllers/api/v1/users/omniauth_callbacks_controller.rb
  app/controllers/api/v1/users/registrations_controller.rb
  app/controllers/api/v1/users/sessions_controller.rb
  app/controllers/concerns/has_doorkeeper_authentication.rb
  config/routes.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
  spec/requests/registrations_controller_spec.rb
  spec/requests/sessions_controller_spec.rb
Labels: type : feature

#54 Release - 0.6.0
  app/controllers/api/v1/search_results_controller.rb
  app/controllers/api/v1/users/omniauth_callbacks_controller.rb
  app/controllers/api/v1/users/registrations_controller.rb
  app/controllers/api/v1/users/sessions_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/error_handleable.rb
  app/controllers/concerns/has_doorkeeper_authentication.rb
  app/controllers/concerns/has_pagination.rb
  app/forms/upload_form.rb
  app/models/search_result.rb
  app/models/user.rb
  app/serializers/application_serializer.rb
  app/serializers/oauth_token_serializer.rb
  app/serializers/search_results_serializer.rb
  app/serializers/user_serializer.rb
  config/initializers/devise.rb
  config/initializers/pagy.rb
  config/locales/activemodel.en.yml
  config/routes.rb
  db/migrate/20230706033605_add_user_id_to_search_results.rb
  db/migrate/20230710023912_rename_uid_for_users.rb
  db/schema.rb
  spec/fabricators/application_fabricator.rb
  spec/fabricators/search_result_fabricator.rb
  spec/fabricators/user_fabricator.rb
  spec/forms/upload_form_spec.rb
  spec/jobs/search_keyword_job_spec.rb
  spec/models/user_spec.rb
  spec/requests/omniauth_callbacks_controller_spec.rb
  spec/requests/registrations_controller_spec.rb
  spec/requests/search_results_controller_spec.rb
  spec/requests/sessions_controller_spec.rb
  spec/support/authentication_helpers.rb
Labels: type : release

#49 [#7] [Backend] As a user, I can receive and verify an verification e-mail
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/users/confirmations_controller.rb
  app/controllers/api/v1/users/sessions_controller.rb
  app/mailers/application_mailer.rb
  app/models/user.rb
  app/serializers/user_serializer.rb
  config/application.yml
  config/environments/production.rb
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20230626042619_devise_create_users.rb
  db/migrate/20230711094816_add_confirmable_to_users.rb
  db/schema.rb
  spec/fabricators/user_fabricator.rb
  spec/requests/confirmations_controller_spec.rb
  spec/requests/sessions_controller_spec.rb
Labels: type : feature

#51 [#20] [Backend] As a user, I can filter which search results contain a specific URL
  app/controllers/api/v1/search_results_controller.rb
  app/queries/search_results_query.rb
  app/serializers/search_results_serializer.rb
  spec/fabricators/search_result_fabricator.rb
  spec/queries/search_results_query_spec.rb
  spec/requests/search_results_controller_spec.rb
Labels: type : feature

#53 [#17] [Backend] As a user, I can filter which search results contain a word in Adwords URLs
  app/controllers/api/v1/search_results_controller.rb
  app/queries/search_results_query.rb
  spec/queries/search_results_query_spec.rb
Labels: type : feature

#50 [#18] [Backend] As a user, I can see the details of a search result
  app/controllers/api/v1/search_results_controller.rb
  app/controllers/application_controller.rb
  app/serializers/search_result_list_serializer.rb
  app/serializers/search_result_serializer.rb
  app/serializers/search_results_serializer.rb
  config/locales/activerecord.en.yml
  config/routes.rb
  spec/requests/search_results_controller_spec.rb
Labels: type : feature

#52 [#16] [Backend] As user, I can download a PDF of the search result
  .github/workflows/test.yml
  .gitignore
  .yarnrc
  Dockerfile
  Gemfile
  Gemfile.lock
  Makefile
  app/controllers/api/v1/exports_controller.rb
  app/serializers/search_result_details_serializer.rb
  config/initializers/grover.rb
  config/locales/activemodel.en.yml
  config/routes.rb
  docker-compose.yml
  package.json
  spec/requests/exports_controller_spec.rb
  yarn.lock
Labels: type : feature

#56 [#55] Update README.md
  README.md
  postman-collection.json
Labels: type : chore

#57 [#21][Backend] As a user, I can filter which search results contain a specific amount of characters
  app/controllers/api/v1/search_results_controller.rb
  app/queries/search_results_query.rb
  app/serializers/search_result_list_serializer.rb
  spec/queries/search_results_query_spec.rb
  spec/requests/search_results_controller_spec.rb
Labels: type : feature

#58 Release - 0.7.0
  .github/workflows/test.yml
  .gitignore
  .yarnrc
  Dockerfile
  Gemfile
  Gemfile.lock
  Makefile
  README.md
  app/controllers/api/v1/exports_controller.rb
  app/controllers/api/v1/search_results_controller.rb
  app/controllers/api/v1/users/confirmations_controller.rb
  app/controllers/api/v1/users/sessions_controller.rb
  app/controllers/application_controller.rb
  app/mailers/application_mailer.rb
  app/models/user.rb
  app/queries/search_results_query.rb
  app/serializers/search_result_details_serializer.rb
  app/serializers/search_result_list_serializer.rb
  app/serializers/search_result_serializer.rb
  app/serializers/search_results_serializer.rb
  app/serializers/user_serializer.rb
  config/application.yml
  config/environments/production.rb
  config/initializers/devise.rb
  config/initializers/grover.rb
  config/locales/activemodel.en.yml
  config/locales/activerecord.en.yml
  config/routes.rb
  db/migrate/20230626042619_devise_create_users.rb
  db/migrate/20230711094816_add_confirmable_to_users.rb
  db/schema.rb
  docker-compose.yml
  package.json
  postman-collection.json
  spec/fabricators/search_result_fabricator.rb
  spec/fabricators/user_fabricator.rb
  spec/queries/search_results_query_spec.rb
  spec/requests/confirmations_controller_spec.rb
  spec/requests/exports_controller_spec.rb
  spec/requests/search_results_controller_spec.rb
  spec/requests/sessions_controller_spec.rb
  yarn.lock
Labels: type : release
